import { defineField, defineType } from "sanity";

export default defineType({
  name: "event",
  title: "Événements",
  type: "document",
  fields: [
    defineField({ name: "title", title: "Titre", type: "string", validation: (Rule) => Rule.required() }),
    defineField({ name: "slug", title: "Slug", type: "slug", options: { source: "title" }, validation: (Rule) => Rule.required() }),
    defineField({ name: "fullName", title: "Nom complet", type: "string" }),
    defineField({ name: "slogan", title: "Slogan", type: "string" }),
    defineField({ name: "dateLabel", title: "Date affichée", type: "string" }),
    defineField({ name: "timeLabel", title: "Ouverture des portes", type: "string" }),
    defineField({ name: "officialStartTimeLabel", title: "Début officiel", type: "string" }),
    defineField({ name: "endTimeLabel", title: "Fin", type: "string" }),
    defineField({ name: "startDateTime", title: "Ouverture des portes — date et heure ISO", type: "datetime" }),
    defineField({ name: "officialStartDateTime", title: "Début officiel — date et heure ISO", type: "datetime" }),
    defineField({ name: "endDateTime", title: "Fin — date et heure ISO", type: "datetime" }),
    defineField({ name: "location", title: "Lieu", type: "string" }),
    defineField({ name: "description", title: "Description", type: "text", rows: 5 }),
    defineField({ name: "totalSeats", title: "Nombre de places", type: "number" }),
    defineField({ name: "program", title: "Programme", type: "array", of: [{ type: "object", fields: [{ name: "time", type: "string" }, { name: "title", type: "string" }, { name: "description", type: "text" }] }] }),
    defineField({ name: "speakers", title: "Intervenants", type: "array", of: [{ type: "reference", to: [{ type: "speaker" }] }] }),
    defineField({ name: "faqs", title: "FAQ de l'événement", type: "array", of: [{ type: "reference", to: [{ type: "faq" }] }] }),
    defineField({ name: "whatsappCta", title: "CTA WhatsApp", type: "string" }),
    defineField({ name: "registrationCta", title: "CTA inscription", type: "string" }),
    defineField({ name: "heroImage", title: "Image hero", type: "image", options: { hotspot: true } }),
    defineField({ name: "emailSubject", title: "Sujet email billet", type: "string" }),
    defineField({ name: "emailBody", title: "Texte email billet", type: "text", rows: 6 }),
    defineField({ name: "seoTitle", title: "Titre SEO", type: "string" }),
    defineField({ name: "metaDescription", title: "Meta description", type: "text", rows: 3 }),
  ],
});
